-- 50 top UK coffee shops (Yorkshire + London priority).
-- Paste into the Supabase SQL Editor (runs as postgres / service role).
-- Requires at least one user to exist in public.reviewers.
-- All rows are idempotent via ON CONFLICT (slug) DO NOTHING.

do $$
declare
  seed_by uuid;
begin
  select id into seed_by from public.reviewers limit 1;

  if seed_by is null then
    raise exception
      'No reviewer found — create at least one account via the app before running this seed.';
  end if;

  insert into public.venues
    (slug, name, address_line1, address_line2, city, postcode, country,
     website, instagram, roasters, brew_methods,
     has_decaf, has_plant_milk, notes, created_by)
  values

  -- ── YORKSHIRE: Leeds ───────────────────────────────────────────────────────

  ('laynes-espresso',
   'Laynes Espresso',
   '16 New Station Street', null,
   'Leeds', 'LS1 5DL', 'GB',
   'https://laynescafe.co.uk', 'laynescafe',
   array['North Star', 'Hasbean', 'Square Mile'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Barista-owned city-centre staple. Rotating guest roasters, exceptional brunch.',
   seed_by),

  ('north-star-coffee-shop',
   'North Star Coffee Shop & General Store',
   'Unit 32, The Boulevard', 'Leeds Dock',
   'Leeds', 'LS10 1PZ', 'GB',
   'https://www.northstarroast.com', 'northstarcoffeeshop',
   array['North Star'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'North Star''s dockside flagship. Full pour-over menu from own-roasted lots.',
   seed_by),

  ('la-bottega-milanese-leeds',
   'La Bottega Milanese',
   '2 Bond Court', null,
   'Leeds', 'LS1 2JZ', 'GB',
   'https://www.labottegamilanese.co.uk', 'labottegamilanese',
   array['La Bottega Milanese'],
   array['espresso'],
   true, true,
   'Italian-style coffee bar and deli. Strong espresso, fresh panini, slick room.',
   seed_by),

  ('out-of-the-woods-water-lane',
   'Out of the Woods',
   '113 Water Lane', null,
   'Leeds', 'LS11 5WD', 'GB',
   'https://outofthewoods.me.uk', 'outofthewoodsuk',
   array['Dark Woods'],
   array['espresso', 'filter'],
   true, true,
   'Canalside woodland-themed café. Dark Woods beans, excellent cake selection.',
   seed_by),

  ('fika-north-headingley',
   'Fika North',
   '94 Otley Road', null,
   'Leeds', 'LS6 4BA', 'GB',
   'https://www.fikanorth.co.uk', 'fikanorth',
   array['Casa Espresso'],
   array['espresso', 'filter'],
   true, true,
   'Swedish-inspired Headingley café. Casa Espresso beans, great bagels.',
   seed_by),

  -- ── YORKSHIRE: Sheffield ───────────────────────────────────────────────────

  ('steam-yard-sheffield',
   'Steam Yard',
   '97 Division Street', 'Aberdeen Court',
   'Sheffield', 'S1 4GE', 'GB',
   'https://steamyard.co.uk', 'steamyard',
   array['Caravan', 'Square Mile'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Buzzy Sheffield indie. Caravan house espresso, rotating guest filter.',
   seed_by),

  ('kilnfolk-coffee-sheffield',
   'Kilnfolk Coffee',
   '50 Clough Road', 'Chaucer Yard',
   'Sheffield', 'S1 4TB', 'GB',
   'https://www.kilnfolk.coffee', 'kilnfolk.coffee',
   array['Dark Woods', 'North Star'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Coffee shop and pottery studio in one. Handmade ceramics on every surface.',
   seed_by),

  ('upshot-espresso-sheffield',
   'Upshot Espresso',
   '355 Glossop Road', null,
   'Sheffield', 'S10 2HP', 'GB',
   null, 'upshotespresso',
   array['Foundry Coffee Roasters'],
   array['espresso', 'filter'],
   true, true,
   'Neighbourhood specialty bar near the university. Local Foundry roast.',
   seed_by),

  -- ── YORKSHIRE: York ────────────────────────────────────────────────────────

  ('spring-espresso-fossgate',
   'Spring Espresso',
   '45 Fossgate', null,
   'York', 'YO1 9TF', 'GB',
   'https://www.springespresso.co.uk', 'springespresso',
   array['Square Mile', 'Spring Espresso'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'York''s most respected specialty stop. Square Mile and own-roasted lots.',
   seed_by),

  ('le-specialty-york',
   'Lè Specialty',
   '23 Fossgate', null,
   'York', 'YO1 9TA', 'GB',
   null, 'lespecialty',
   array['North Star', 'Dark Woods'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'Small Fossgate specialty bar. Curated Yorkshire roasters, excellent pour-overs.',
   seed_by),

  -- ── YORKSHIRE: Harrogate ───────────────────────────────────────────────────

  ('hoxton-north-harrogate',
   'Hoxton North',
   '1 Royal Parade', null,
   'Harrogate', 'HG1 2SZ', 'GB',
   'https://hoxtonnorth.com', 'hoxtonnorth',
   array['Union Hand-Roasted', 'Square Mile'],
   array['espresso', 'filter', 'pour_over', 'aeropress'],
   true, true,
   'London-feel brew bar in the Dales. Rotating seasonal roasters, excellent food.',
   seed_by),

  ('brood-coffee-harrogate',
   'Brood Coffee House',
   '27 Commercial Street', null,
   'Harrogate', 'HG1 1UB', 'GB',
   'https://broodcoffeehouse.com', 'broodcoffee',
   array['North Star'],
   array['espresso', 'filter', 'batch_brew'],
   true, true,
   'Cosy Harrogate café with North Star beans and an excellent brunch menu.',
   seed_by),

  ('nomad-cafe-harrogate',
   'Nomad Café & Deli',
   '29A Beulah Street', null,
   'Harrogate', 'HG1 1QH', 'GB',
   'https://nomad-cafe.co.uk', 'nomadcafeharrogate',
   array['Dark Woods', 'Casa Espresso'],
   array['espresso', 'filter'],
   true, true,
   'Dog-friendly deli café. Yorkshire roasters, good sandwiches and pastries.',
   seed_by),

  -- ── LONDON ─────────────────────────────────────────────────────────────────

  ('prufrock-coffee-leather-lane',
   'Prufrock Coffee',
   '23-25 Leather Lane', null,
   'London', 'EC1N 7TE', 'GB',
   'https://prufrockcoffee.com', 'prufrockcoffee',
   array['Square Mile'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'Clerkenwell institution co-founded by World Barista Champion Gwilym Davies.',
   seed_by),

  ('kaffeine-fitzrovia',
   'Kaffeine',
   '66 Great Titchfield Street', null,
   'London', 'W1W 7QJ', 'GB',
   'https://kaffeine.co.uk', 'kaffeinelondon',
   array['Square Mile'],
   array['espresso', 'filter', 'cold_brew'],
   true, true,
   'Tight Fitzrovia shop with reliable espresso. Morning queue is the real deal.',
   seed_by),

  ('kaffeine-eastcastle',
   'Kaffeine Eastcastle',
   '15 Eastcastle Street', null,
   'London', 'W1T 3AY', 'GB',
   'https://kaffeine.co.uk', 'kaffeinelondon',
   array['Square Mile'],
   array['espresso', 'filter', 'cold_brew'],
   true, true,
   'Second Kaffeine site a minute from the original. Same standard, slightly more seats.',
   seed_by),

  ('ozone-coffee-roasters-shoreditch',
   'Ozone Coffee Roasters',
   '11 Leonard Street', null,
   'London', 'EC2A 4AQ', 'GB',
   'https://ozonecoffee.co.uk', 'ozonecoffeeuk',
   array['Ozone'],
   array['espresso', 'filter', 'batch_brew'],
   true, true,
   'NZ-origin roastery and full kitchen in Shoreditch. Own-roasted beans shine on filter.',
   seed_by),

  ('workshop-coffee-belgravia',
   'Workshop Coffee',
   '22 Eccleston Street', null,
   'London', 'SW1W 9LT', 'GB',
   'https://workshopcoffee.com', 'workshopcoffee',
   array['Workshop'],
   array['espresso', 'filter', 'pour_over', 'cold_brew'],
   true, true,
   'Belgravia café and coffee academy. Monthly-changing pour-over menu, serious kit.',
   seed_by),

  ('monmouth-coffee-borough',
   'Monmouth Coffee Company',
   '2 Park Street', null,
   'London', 'SE1 9AB', 'GB',
   'https://www.monmouthcoffee.co.uk', 'monmouthcoffee',
   array['Monmouth'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'Borough Market anchor since the nineties. Single-origin focus, always packed.',
   seed_by),

  ('monmouth-coffee-covent-garden',
   'Monmouth Coffee Company Covent Garden',
   '27 Monmouth Street', null,
   'London', 'WC2H 9EU', 'GB',
   'https://www.monmouthcoffee.co.uk', 'monmouthcoffee',
   array['Monmouth'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'The original Monmouth shop. Small, packed, and worth every minute of the queue.',
   seed_by),

  ('catalyst-coffee-holborn',
   'Catalyst',
   '48 Gray''s Inn Road', null,
   'London', 'WC1X 8LT', 'GB',
   'https://catalyst.coffee', 'catalyst__cafe',
   array['Catalyst'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'In-house roastery in the basement, Scandi-cool room above. Own filter and espresso.',
   seed_by),

  ('rosslyn-coffee-london-wall',
   'Rosslyn Coffee',
   '118 London Wall', null,
   'London', 'EC2Y 5JA', 'GB',
   'https://www.rosslyncoffee.com', 'rosslyncoffee',
   array['Square Mile', 'Workshop', 'Has Bean'],
   array['espresso', 'filter', 'pour_over', 'cold_brew'],
   true, true,
   'Award-winning City specialty. Extensive filter menu, rotating guest roasters.',
   seed_by),

  ('rosslyn-coffee-queen-victoria',
   'Rosslyn Coffee Queen Victoria Street',
   '78 Queen Victoria Street', null,
   'London', 'EC4N 4SJ', 'GB',
   'https://www.rosslyncoffee.com', 'rosslyncoffee',
   array['Square Mile', 'Workshop', 'Has Bean'],
   array['espresso', 'filter', 'pour_over', 'cold_brew'],
   true, true,
   'Second Rosslyn City site. Same meticulous filter programme, quieter weekends.',
   seed_by),

  ('caravan-coffee-kings-cross',
   'Caravan Coffee Roasters',
   '1 Granary Square', null,
   'London', 'N1C 4AA', 'GB',
   'https://caravanandco.com', 'caravanroastery',
   array['Caravan'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'Roastery restaurant in an iconic King''s Cross grainstore. Own seasonal lots.',
   seed_by),

  ('dark-arts-coffee-hackney',
   'Dark Arts Coffee',
   '1-5 Rosina Street', null,
   'London', 'E9 6JH', 'GB',
   'https://www.darkartscoffee.co.uk', 'darkartscoffee',
   array['Dark Arts'],
   array['espresso', 'filter', 'batch_brew'],
   true, true,
   'Hackney roastery-café with cult branding. Own-roast, no-nonsense brews.',
   seed_by),

  ('shoreditch-grind',
   'Shoreditch Grind',
   '213 Old Street', null,
   'London', 'EC1V 9NR', 'GB',
   'https://grind.co.uk', 'grind',
   array['Grind'],
   array['espresso', 'cold_brew'],
   true, true,
   'Cylindrical Old Street corner café. Specialty espresso by day, cocktails at night.',
   seed_by),

  ('allpress-espresso-shoreditch',
   'Allpress Espresso',
   '58 Redchurch Street', null,
   'London', 'E2 7DP', 'GB',
   'https://www.allpressespresso.com', 'allpressespressouk',
   array['Allpress'],
   array['espresso', 'filter'],
   true, true,
   'Original London outpost of the NZ-founded roastery. No-frills espresso bar on Redchurch St.',
   seed_by),

  ('association-coffee-creechurch',
   'Association Coffee',
   '10-12 Creechurch Lane', null,
   'London', 'EC3A 5AY', 'GB',
   null, 'associationcoffee',
   array['Square Mile', 'Caravan', 'Workshop'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'City of London specialty. Curated rotating roaster selection, excellent filter bar.',
   seed_by),

  ('association-coffee-ludgate-hill',
   'Association Coffee Ludgate Hill',
   '56 Ludgate Hill', null,
   'London', 'EC4M 7HX', 'GB',
   null, 'associationcoffee',
   array['Square Mile', 'Caravan', 'Workshop'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Second Association site near St Paul''s. Same rotating roaster programme.',
   seed_by),

  ('attendant-coffee-fitzrovia',
   'Attendant Coffee Roasters',
   '27A Foley Street', null,
   'London', 'W1W 6DY', 'GB',
   'https://attendantcoffee.com', 'attendantcoffee',
   array['Attendant'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Former Victorian toilet turned specialty café. Own-roasted seasonal lots.',
   seed_by),

  ('notes-coffee-covent-garden',
   'Notes Coffee Roasters',
   '31 St Martin''s Lane', null,
   'London', 'WC2N 4ER', 'GB',
   'https://notescoffee.com', 'notescoffee',
   array['Notes'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Specialty roastery café by day, wine bar by night. Own-roasted single origins.',
   seed_by),

  ('nude-espresso-spitalfields',
   'Nude Espresso',
   '26 Hanbury Street', null,
   'London', 'E1 6QR', 'GB',
   'https://www.nudeespresso.com', 'nudeespresso',
   array['Nude'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Spitalfields pioneer since 2008. Own-roast across the road, good brunch.',
   seed_by),

  ('federation-coffee-brixton',
   'Federation Coffee',
   '77-78 Coldharbour Lane', 'Brixton Village',
   'London', 'SW9 8PS', 'GB',
   'https://federation.coffee', 'federationcoffee',
   array['Curve Roasters'],
   array['espresso', 'filter', 'batch_brew'],
   true, true,
   'Brixton Village market café. Lively atmosphere, Curve Roasters house blend.',
   seed_by),

  ('department-of-coffee-leather-lane',
   'Department of Coffee and Social Affairs',
   '14-16 Leather Lane', null,
   'London', 'EC1N 7SU', 'GB',
   'https://www.departmentofcoffee.com', 'docoffeelondon',
   array['Has Bean', 'Department of Coffee'],
   array['espresso', 'filter', 'batch_brew'],
   true, true,
   'Social enterprise multi-roaster café near Chancery Lane. Community focus.',
   seed_by),

  ('store-street-espresso-bloomsbury',
   'Store Street Espresso',
   '40 Store Street', null,
   'London', 'WC1E 7DB', 'GB',
   null, 'storestreetespresso',
   array['Square Mile'],
   array['espresso', 'filter'],
   true, true,
   'Tiny Bloomsbury corner café. Square Mile espresso, great pastries.',
   seed_by),

  ('the-espresso-room-bloomsbury',
   'The Espresso Room',
   '31-35 Great Ormond Street', null,
   'London', 'WC1N 3HZ', 'GB',
   null, 'theespressoroom',
   array['Workshop', 'Square Mile'],
   array['espresso', 'filter'],
   true, true,
   'WC1 neighbourhood favourite opposite Great Ormond Street Hospital.',
   seed_by),

  ('gentlemen-baristas-union-street',
   'The Gentlemen Baristas',
   '63 Union Street', null,
   'London', 'SE1 1SG', 'GB',
   'https://www.thegentlemenbaristas.com', 'gentlemenbaristas',
   array['The Gentlemen Baristas'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'Own-roast specialty in Southwark. Dapper branding, good food menu.',
   seed_by),

  ('fernandez-and-wells-soho',
   'Fernandez & Wells',
   '73 Beak Street', null,
   'London', 'W1F 9SR', 'GB',
   'https://www.fernandezandwells.com', 'fernandezandwells',
   array['Has Bean'],
   array['espresso', 'filter'],
   true, true,
   'Soho wine-bar-meets-café. Excellent espresso, Spanish charcuterie and cheese.',
   seed_by),

  ('climpson-and-sons-broadway-market',
   'Climpson & Sons',
   '67 Broadway Market', null,
   'London', 'E8 4PH', 'GB',
   'https://www.climpsonandsons.com', 'climpsonandsons',
   array['Climpson & Sons'],
   array['espresso', 'filter', 'pour_over', 'aeropress'],
   true, true,
   'Hackney roastery icon. Own-roasted lots, packed on weekend market days.',
   seed_by),

  ('story-coffee-clapham',
   'Story Coffee',
   '115 St John''s Hill', null,
   'London', 'SW11 1SZ', 'GB',
   null, 'storycoffeelondon',
   array['Workshop', 'Square Mile', 'Dark Arts'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Neighbourhood specialty near Clapham Junction. Rotating guest roasters.',
   seed_by),

  ('tapped-and-packed-fitzrovia',
   'Tapped & Packed',
   '114 Tottenham Court Road', null,
   'London', 'W1T 5AH', 'GB',
   'https://tappedandpacked.co.uk', 'tappedandpacked',
   array['Square Mile', 'Has Bean', 'Workshop'],
   array['espresso', 'filter', 'pour_over', 'aeropress', 'batch_brew'],
   true, true,
   'One of the longest brew-method menus in London. Serious filter credentials.',
   seed_by),

  ('13th-floor-coffee-stoke-newington',
   '13th Floor Coffee',
   '11 Stoke Newington Church Street', null,
   'London', 'N16 0UH', 'GB',
   null, '13thfloorcoffee',
   array['Square Mile', 'Caravan'],
   array['espresso', 'filter'],
   true, true,
   'Converted horse box outside St Mary''s Church. Specialty coffee and baked treats.',
   seed_by),

  ('vagabond-coffee-kilburn',
   'Vagabond Coffee',
   '242 Kilburn Lane', null,
   'London', 'W10 4BB', 'GB',
   null, 'vagabondcoffee',
   array['Has Bean', 'Square Mile'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'West London neighbourhood café. Relaxed specialty stop with good filter options.',
   seed_by),

  ('timberyard-covent-garden',
   'Timberyard',
   '7 Upper St Martin''s Lane', null,
   'London', 'WC2H 9DL', 'GB',
   'https://timberyardlondon.com', 'timberyardlondon',
   array['Workshop', 'Square Mile'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'Sprawling co-work-friendly Covent Garden café. Excellent filter range, all-day food.',
   seed_by),

  ('brickwood-coffee-clapham',
   'Brickwood Coffee',
   '16 Clapham Common South Side', null,
   'London', 'SW4 7AB', 'GB',
   'https://brickwoodcoffee.com', 'brickwoodcoffee',
   array['Union Hand-Roasted'],
   array['espresso', 'filter', 'batch_brew'],
   true, true,
   'South London brunch and specialty café. Big weekend queues, worth the wait.',
   seed_by),

  ('origin-coffee-shoreditch',
   'Origin Coffee Roasters',
   '65 Charlotte Road', null,
   'London', 'EC2A 3PE', 'GB',
   'https://www.origincoffee.co.uk', 'origincoffeeroasters',
   array['Origin'],
   array['espresso', 'filter', 'pour_over', 'cold_brew'],
   true, true,
   'Cornwall roastery''s London flagship. Direct-trade focus, standout filter bar.',
   seed_by),

  ('lantana-cafe-fitzrovia',
   'Lantana Cafe',
   '13 Charlotte Place', null,
   'London', 'W1T 1SN', 'GB',
   'https://lantanacafe.co.uk', 'lantanacafe',
   array['Has Bean', 'Caravan'],
   array['espresso', 'filter', 'batch_brew'],
   true, true,
   'Australian-style all-day café in Fitzrovia. Specialty coffee, excellent brunch.',
   seed_by),

  ('flat-white-soho',
   'Flat White',
   '17 Berwick Street', null,
   'London', 'W1F 0PT', 'GB',
   null, 'flatwhitesoho',
   array['Square Mile'],
   array['espresso', 'filter'],
   true, true,
   'Soho original that helped kickstart London''s flat-white era. Always lively.',
   seed_by),

  ('black-lab-coffee-waterloo',
   'The Black Lab Coffee House',
   '7A Lower Marsh', null,
   'London', 'SE1 7RJ', 'GB',
   null, 'blacklabcoffee',
   array['Has Bean', 'Union Hand-Roasted'],
   array['espresso', 'filter', 'pour_over'],
   true, true,
   'Relaxed Lower Marsh neighbourhood café. Good pour-over selection, dog-friendly.',
   seed_by),

  ('redemption-roasters-marylebone',
   'Redemption Roasters',
   '4 Market Place', null,
   'London', 'W1W 8AJ', 'GB',
   'https://www.redemptionroasters.com', 'redemptionroasters',
   array['Redemption Roasters'],
   array['espresso', 'filter', 'pour_over', 'batch_brew'],
   true, true,
   'Social enterprise roastery-café training ex-offenders in specialty coffee.',
   seed_by)

  on conflict (slug) do nothing;

end $$;
