/**
 * UK region definitions.
 *
 * CITY_TO_REGION maps the lowercased, hyphenated city name to a region id.
 * Any city not in this map falls back to its own id (so it still works as a
 * filter — it just won't be grouped with others). Add cities here as needed;
 * the rest of the app derives everything from this single source.
 */

export const CITY_TO_REGION: Record<string, string> = {
  // ── London ──────────────────────────────────────────────────────────────
  london: "london",

  // ── Yorkshire ───────────────────────────────────────────────────────────
  leeds: "yorkshire",
  sheffield: "yorkshire",
  york: "yorkshire",
  bradford: "yorkshire",
  hull: "yorkshire",
  "kingston-upon-hull": "yorkshire",
  huddersfield: "yorkshire",
  wakefield: "yorkshire",
  halifax: "yorkshire",
  doncaster: "yorkshire",
  rotherham: "yorkshire",
  barnsley: "yorkshire",
  harrogate: "yorkshire",
  scarborough: "yorkshire",
  holmfirth: "yorkshire",
  skipton: "yorkshire",
  ilkley: "yorkshire",
  knaresborough: "yorkshire",
  beverley: "yorkshire",
  ripon: "yorkshire",
  selby: "yorkshire",
  pontefract: "yorkshire",
  castleford: "yorkshire",
  keighley: "yorkshire",
  bingley: "yorkshire",
  dewsbury: "yorkshire",
  batley: "yorkshire",
  morley: "yorkshire",
  wetherby: "yorkshire",
  otley: "yorkshire",
  hebden: "yorkshire",
  "hebden-bridge": "yorkshire",

  // ── North West ──────────────────────────────────────────────────────────
  manchester: "north-west",
  salford: "north-west",
  liverpool: "north-west",
  chester: "north-west",
  lancaster: "north-west",
  blackpool: "north-west",
  preston: "north-west",
  bolton: "north-west",
  oldham: "north-west",
  stockport: "north-west",
  rochdale: "north-west",
  wigan: "north-west",
  warrington: "north-west",
  burnley: "north-west",
  blackburn: "north-west",
  carlisle: "north-west",
  kendal: "north-west",
  morecambe: "north-west",
  southport: "north-west",
  "st-helens": "north-west",
  birkenhead: "north-west",
  wirral: "north-west",
  altrincham: "north-west",
  sale: "north-west",
  stretford: "north-west",
  eccles: "north-west",
  leigh: "north-west",
  macclesfield: "north-west",
  wilmslow: "north-west",
  crewe: "north-west",
  northwich: "north-west",
  runcorn: "north-west",
  widnes: "north-west",
  halton: "north-west",
  chorley: "north-west",
  accrington: "north-west",
  barrow: "north-west",
  "barrow-in-furness": "north-west",
  penrith: "north-west",

  // ── North East ──────────────────────────────────────────────────────────
  newcastle: "north-east",
  "newcastle-upon-tyne": "north-east",
  sunderland: "north-east",
  durham: "north-east",
  middlesbrough: "north-east",
  gateshead: "north-east",
  "south-shields": "north-east",
  hartlepool: "north-east",
  darlington: "north-east",
  "stockton-on-tees": "north-east",
  stockton: "north-east",
  blyth: "north-east",
  hexham: "north-east",
  "bishop-auckland": "north-east",
  consett: "north-east",
  whitby: "north-east",

  // ── West Midlands ────────────────────────────────────────────────────────
  birmingham: "west-midlands",
  coventry: "west-midlands",
  wolverhampton: "west-midlands",
  walsall: "west-midlands",
  solihull: "west-midlands",
  "west-bromwich": "west-midlands",
  "stoke-on-trent": "west-midlands",
  stoke: "west-midlands",
  lichfield: "west-midlands",
  stafford: "west-midlands",
  telford: "west-midlands",
  shrewsbury: "west-midlands",
  hereford: "west-midlands",
  worcester: "west-midlands",
  redditch: "west-midlands",
  bromsgrove: "west-midlands",
  tamworth: "west-midlands",
  cannock: "west-midlands",
  "burton-upon-trent": "west-midlands",
  "burton-on-trent": "west-midlands",
  nuneaton: "west-midlands",
  "royal-leamington-spa": "west-midlands",
  "leamington-spa": "west-midlands",
  warwick: "west-midlands",
  stratford: "west-midlands",
  "stratford-upon-avon": "west-midlands",
  dudley: "west-midlands",
  "west-midlands": "west-midlands",

  // ── East Midlands ────────────────────────────────────────────────────────
  nottingham: "east-midlands",
  leicester: "east-midlands",
  derby: "east-midlands",
  lincoln: "east-midlands",
  northampton: "east-midlands",
  mansfield: "east-midlands",
  loughborough: "east-midlands",
  chesterfield: "east-midlands",
  kettering: "east-midlands",
  corby: "east-midlands",
  grantham: "east-midlands",
  stamford: "east-midlands",
  matlock: "east-midlands",
  "long-eaton": "east-midlands",
  ilkeston: "east-midlands",
  "melton-mowbray": "east-midlands",
  hinckley: "east-midlands",
  rugby: "east-midlands",
  "market-harborough": "east-midlands",
  boston: "east-midlands",
  spalding: "east-midlands",
  skegness: "east-midlands",
  glossop: "east-midlands",

  // ── East of England ──────────────────────────────────────────────────────
  cambridge: "east-of-england",
  norwich: "east-of-england",
  ipswich: "east-of-england",
  peterborough: "east-of-england",
  colchester: "east-of-england",
  chelmsford: "east-of-england",
  luton: "east-of-england",
  bedford: "east-of-england",
  ely: "east-of-england",
  "st-albans": "east-of-england",
  hertford: "east-of-england",
  watford: "east-of-england",
  stevenage: "east-of-england",
  "bury-st-edmunds": "east-of-england",
  "king's-lynn": "east-of-england",
  "kings-lynn": "east-of-england",
  "great-yarmouth": "east-of-england",
  lowestoft: "east-of-england",
  harlow: "east-of-england",
  basildon: "east-of-england",
  "southend-on-sea": "east-of-england",
  southend: "east-of-england",
  braintree: "east-of-england",
  "clacton-on-sea": "east-of-england",
  hatfield: "east-of-england",
  "hemel-hempstead": "east-of-england",
  welwyn: "east-of-england",
  letchworth: "east-of-england",
  hitchin: "east-of-england",

  // ── South East ───────────────────────────────────────────────────────────
  brighton: "south-east",
  hove: "south-east",
  oxford: "south-east",
  southampton: "south-east",
  portsmouth: "south-east",
  reading: "south-east",
  canterbury: "south-east",
  guildford: "south-east",
  maidstone: "south-east",
  basingstoke: "south-east",
  winchester: "south-east",
  worthing: "south-east",
  crawley: "south-east",
  eastbourne: "south-east",
  "tunbridge-wells": "south-east",
  "royal-tunbridge-wells": "south-east",
  folkestone: "south-east",
  dover: "south-east",
  margate: "south-east",
  ramsgate: "south-east",
  hastings: "south-east",
  chichester: "south-east",
  "bognor-regis": "south-east",
  fareham: "south-east",
  gosport: "south-east",
  aldershot: "south-east",
  farnham: "south-east",
  woking: "south-east",
  epsom: "south-east",
  redhill: "south-east",
  reigate: "south-east",
  horsham: "south-east",
  "haywards-heath": "south-east",
  "burgess-hill": "south-east",
  lewes: "south-east",
  ashford: "south-east",
  tonbridge: "south-east",
  sevenoaks: "south-east",
  gravesend: "south-east",
  rochester: "south-east",
  chatham: "south-east",
  gillingham: "south-east",
  sittingbourne: "south-east",
  whitstable: "south-east",
  "herne-bay": "south-east",
  "milton-keynes": "south-east",
  aylesbury: "south-east",
  "high-wycombe": "south-east",
  maidenhead: "south-east",
  slough: "south-east",
  windsor: "south-east",
  bracknell: "south-east",
  newbury: "south-east",
  andover: "south-east",
  eastleigh: "south-east",
  romsey: "south-east",
  "isle-of-wight": "south-east",
  newport: "south-east",
  ryde: "south-east",

  // ── South West ───────────────────────────────────────────────────────────
  bristol: "south-west",
  bath: "south-west",
  exeter: "south-west",
  plymouth: "south-west",
  bournemouth: "south-west",
  gloucester: "south-west",
  cheltenham: "south-west",
  swindon: "south-west",
  truro: "south-west",
  salisbury: "south-west",
  taunton: "south-west",
  poole: "south-west",
  dorchester: "south-west",
  yeovil: "south-west",
  torquay: "south-west",
  paignton: "south-west",
  "newton-abbot": "south-west",
  barnstaple: "south-west",
  bideford: "south-west",
  "weston-super-mare": "south-west",
  bridgwater: "south-west",
  glastonbury: "south-west",
  wells: "south-west",
  stroud: "south-west",
  cirencester: "south-west",
  chippenham: "south-west",
  trowbridge: "south-west",
  devizes: "south-west",
  marlborough: "south-west",
  weymouth: "south-west",
  christchurch: "south-west",
  penzance: "south-west",
  falmouth: "south-west",
  newquay: "south-west",
  "st-ives": "south-west",
  totnes: "south-west",
  "okehampton": "south-west",
  tiverton: "south-west",

  // ── Scotland ─────────────────────────────────────────────────────────────
  edinburgh: "scotland",
  glasgow: "scotland",
  aberdeen: "scotland",
  dundee: "scotland",
  inverness: "scotland",
  stirling: "scotland",
  "st-andrews": "scotland",
  perth: "scotland",
  falkirk: "scotland",
  paisley: "scotland",
  hamilton: "scotland",
  livingston: "scotland",
  "east-kilbride": "scotland",
  motherwell: "scotland",
  greenock: "scotland",
  ayr: "scotland",
  kilmarnock: "scotland",
  dunfermline: "scotland",
  kirkcaldy: "scotland",
  glenrothes: "scotland",
  bathgate: "scotland",
  dumfries: "scotland",
  "fort-william": "scotland",
  oban: "scotland",
  elgin: "scotland",
  "st.-andrews": "scotland",

  // ── Wales ────────────────────────────────────────────────────────────────
  cardiff: "wales",
  swansea: "wales",
  wrexham: "wales",
  aberystwyth: "wales",
  bangor: "wales",
  llandudno: "wales",
  caernarfon: "wales",
  "merthyr-tydfil": "wales",
  pontypridd: "wales",
  barry: "wales",
  penarth: "wales",
  bridgend: "wales",
  "port-talbot": "wales",
  neath: "wales",
  llanelli: "wales",
  carmarthen: "wales",
  tenby: "wales",
  pembroke: "wales",
  haverfordwest: "wales",
  brecon: "wales",
  abergavenny: "wales",
  monmouth: "wales",
  rhyl: "wales",
  colwyn: "wales",
  "colwyn-bay": "wales",

  // ── Northern Ireland ─────────────────────────────────────────────────────
  belfast: "northern-ireland",
  derry: "northern-ireland",
  londonderry: "northern-ireland",
  lisburn: "northern-ireland",
  armagh: "northern-ireland",
  newry: "northern-ireland",
  antrim: "northern-ireland",
  ballymena: "northern-ireland",
  coleraine: "northern-ireland",
  enniskillen: "northern-ireland",
  omagh: "northern-ireland",
  dungannon: "northern-ireland",
  newtownards: "northern-ireland",
  newtownabbey: "northern-ireland",
  carrickfergus: "northern-ireland",
  larne: "northern-ireland",
  lurgan: "northern-ireland",
  portadown: "northern-ireland",
  craigavon: "northern-ireland",
};

export const REGION_NAMES: Record<string, string> = {
  london: "London",
  yorkshire: "Yorkshire",
  "north-west": "North West",
  "north-east": "North East",
  "west-midlands": "West Midlands",
  "east-midlands": "East Midlands",
  "east-of-england": "East of England",
  "south-east": "South East",
  "south-west": "South West",
  scotland: "Scotland",
  wales: "Wales",
  "northern-ireland": "Northern Ireland",
};

/**
 * Returns the region id for a given city name.
 * Falls back to the normalised city id if not mapped, so unmapped cities
 * still display and filter correctly as single-city "regions".
 */
export function regionIdFromCityName(cityName: string): string {
  const cityId = cityName.trim().toLowerCase().replace(/\s+/g, "-");
  return CITY_TO_REGION[cityId] ?? cityId;
}

/**
 * Human-readable name for a region id.
 * For known regions this is the proper name; for unknown ids the id itself
 * is title-cased as a reasonable fallback.
 */
export function regionDisplayName(regionId: string, fallback?: string): string {
  return (
    REGION_NAMES[regionId] ??
    fallback ??
    regionId
      .split("-")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ")
  );
}
