import Link from "next/link";

export const metadata = {
  title: "About Calibration Reviewers — Coffeesnob",
  description:
    "How and why Coffeesnob uses AI-assisted calibration reviewers in the fictional city of Bramford.",
};

export default function CalibrationPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12 prose prose-sm">
      <h1>Calibration Reviewers &amp; the City of Bramford</h1>

      <p>
        Coffeesnob's leaderboards are powered by a weighted-credibility algorithm
        that learns which reviewers have consistent, discerning taste over time.
        Before we opened to real users, the algorithm had no data to learn from —
        a cold-start problem.
      </p>

      <p>
        Our solution: a fictional city called <strong>Bramford</strong>, populated
        by a panel of AI-assisted calibration reviewers.
      </p>

      <h2>What is Bramford?</h2>
      <p>
        Bramford is a fictional UK-coastal city with a rich (invented) third-wave
        coffee scene. Its venues don't exist. Its reviewers are synthetic personas
        — each with a distinct voice, set of opinions, and taste profile — running
        on a daily schedule and reviewing Bramford's fictional cafés.
      </p>
      <p>
        You can browse Bramford, read its reviews, and see how the leaderboard
        evolves. Think of it as a living demonstration of the algorithm in action,
        before real-city data arrives.
      </p>

      <h2>How are the reviews generated?</h2>
      <p>
        Each calibration reviewer has a hand-authored persona: a biography, a
        voice register, and a taste vector that defines what they care about in
        coffee. A daily process uses this persona, the venue's characteristics,
        and a large language model to write a review that reflects the reviewer's
        opinions.
      </p>
      <p>
        The scores — coffee quality, vibe — are derived deterministically from
        the taste vector and venue attributes. The prose is generated by the LLM
        within those constraints. We spot-check for voice consistency and quality.
      </p>

      <h2>Does this affect real-city leaderboards?</h2>
      <p>
        No. Calibration reviewers only post reviews of Bramford venues.
        Real-city leaderboards — London, Bristol, Edinburgh — are 100% from
        real human reviewers. The algorithm's credibility calibration uses
        only real reviewers as its baseline, so the synthetic population
        doesn't contaminate it.
      </p>
      <p>
        The purpose of Bramford is to give the algorithm enough data to work
        properly before real-city density is high enough to do the same job.
      </p>

      <h2>Why tell us this?</h2>
      <p>
        Because the honest answer is the only answer worth giving.
        Coffeesnob's value is trustworthy signal about real coffee. Using hidden
        synthetic data to inflate that signal would undermine the whole point.
        Bramford is clearly labelled, clearly fictional, and clearly separate
        from real-city content.
      </p>

      <p className="text-sm text-muted-foreground">
        <Link href="/" className="underline">
          ← Back to home
        </Link>
      </p>
    </main>
  );
}
